pretrained_ControlNet_Model_path: "/media/dlz/Data/model_download/lllyasviel_sd-controlnet-openpose"
pretrained_inpaint_Model_path: "/media/dlz/Data/model_download/runwayml_stable-diffusion-inpainting"


save_path: '/media/dlz/Data/workspace/my_work/VideoSD_v1_2/input/github_test/output'

prompt_bg:
  - "Waves and white clouds"
prompt_obj:
  - "Iron Man"


negative_prompt_bg:
  - "Nobody."
negative_prompt_obj:
  - "longbody, Texts,lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer difits, cropped, worst quality, low quality, deformed body, bloated, ugly, unrealistic"

seed_bg: 198
seed_obj: 111


pose_image_path: "/media/dlz/Data/workspace/my_work/VideoSD_v1_2/input/github_test/4"



crop_size: 176

frame_num: 8

org_bg_image_path: '/media/dlz/Data/workspace/my_work/VideoSD_v1_2/input/github_test/bg'

